export const questions = [
  // ── TIER 1: BUSINESS PROFILE ──────────────────────────────────────────
  {
    id: 'q1',
    tier: 1,
    category: 'Practice Size',
    question: 'How many attorneys are currently at this firm?',
    helper: 'Larger firms often have higher marketing budgets and more competitive keywords.',
    type: 'single',
    allowNote: true,
    options: [
      { value: 'solo', label: 'Solo Practitioner', desc: '1 attorney', score: 4 },
      { value: 'small', label: 'Small Firm', desc: '2–5 attorneys', score: 6 },
      { value: 'mid', label: 'Mid-Size Firm', desc: '6–20 attorneys', score: 8 },
      { value: 'large', label: 'Large Firm', desc: '20+ attorneys', score: 10 },
    ],
  },
  {
    id: 'q2',
    tier: 1,
    category: 'Practice Area',
    question: 'What is the firm\'s primary practice area?',
    helper: 'High-intent practice areas tend to have strong PPC performance.',
    type: 'single',
    allowNote: false,
    options: [
      { value: 'personal_injury', label: 'Personal Injury', score: 10 },
      { value: 'criminal', label: 'Criminal Defense', score: 9 },
      { value: 'family', label: 'Family Law / Divorce', score: 9 },
      { value: 'immigration', label: 'Immigration', score: 8 },
      { value: 'business', label: 'Business / Commercial', score: 7 },
      { value: 'estate', label: 'Estate Planning / Probate', score: 6 },
      { value: 'other', label: 'Other', score: 5 },
    ],
  },
  {
    id: 'q3',
    tier: 1,
    category: 'Market',
    question: 'What geographic market does the firm primarily serve?',
    type: 'single',
    options: [
      { value: 'major_metro', label: 'Major Metro (NYC, LA, Chicago, etc.)', score: 10 },
      { value: 'mid_city', label: 'Mid-size City (250k–1M population)', score: 8 },
      { value: 'suburban', label: 'Suburban / Smaller City', score: 6 },
      { value: 'rural', label: 'Rural / Small Town', score: 4 },
    ],
  },
  {
    id: 'q4',
    tier: 1,
    category: 'Client Volume',
    question: 'How many new clients does the firm take on per month?',
    helper: 'This helps us understand their current capacity and growth appetite.',
    type: 'single',
    allowNote: true,
    options: [
      { value: 'less5', label: 'Fewer than 5', score: 3 },
      { value: '5to15', label: '5 – 15 clients', score: 6 },
      { value: '15to40', label: '15 – 40 clients', score: 9 },
      { value: 'more40', label: '40+ clients', score: 10 },
    ],
  },

  // ── TIER 2: DIGITAL READINESS ──────────────────────────────────────────
  {
    id: 'q5',
    tier: 2,
    category: 'Website',
    question: 'How would you describe the firm\'s current website?',
    helper: 'Landing page quality directly impacts PPC conversion rates.',
    type: 'single',
    allowNote: true,
    options: [
      { value: 'modern', label: 'Modern, fast, and optimised for conversions', score: 10 },
      { value: 'decent', label: 'Decent but could be improved', score: 7 },
      { value: 'outdated', label: 'Outdated or slow', score: 4 },
      { value: 'none', label: 'No website / basic directory listing only', score: 1 },
    ],
  },
  {
    id: 'q6',
    tier: 2,
    category: 'Current Ads',
    question: 'Is the firm currently running any paid advertising?',
    type: 'single',
    allowNote: true,
    options: [
      { value: 'active_ppc', label: 'Yes – active Google Ads campaigns', score: 8 },
      { value: 'tried_failed', label: 'Tried it before but stopped (poor results)', score: 9 },
      { value: 'other_ads', label: 'Other paid ads (social, directory, etc.)', score: 6 },
      { value: 'none', label: 'No paid advertising at all', score: 7 },
    ],
  },
  {
    id: 'q7',
    tier: 2,
    category: 'Lead Sources',
    question: 'Where does the firm currently get most of its new clients?',
    type: 'multi',
    optional: true,
    allowNote: false,
    options: [
      { value: 'referral', label: 'Word of mouth / referrals' },
      { value: 'organic_seo', label: 'Organic Google search (SEO)' },
      { value: 'ppc', label: 'Paid Google Ads' },
      { value: 'social', label: 'Social media' },
      { value: 'directories', label: 'Legal directories (Avvo, FindLaw, etc.)' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q8',
    tier: 2,
    category: 'Tracking',
    question: 'Does the firm track leads and measure where clients come from?',
    helper: 'Firms with tracking in place are far easier to demonstrate ROI to.',
    type: 'single',
    options: [
      { value: 'full', label: 'Yes – full CRM and call tracking', score: 10 },
      { value: 'partial', label: 'Partial – some tracking but not complete', score: 6 },
      { value: 'basic', label: 'Basic – just Google Analytics', score: 4 },
      { value: 'none', label: 'No tracking at all', score: 2 },
    ],
  },

  // ── TIER 3: PPC POTENTIAL ──────────────────────────────────────────────
  {
    id: 'q9',
    tier: 3,
    category: 'Budget',
    question: 'What monthly ad spend budget is the firm open to?',
    helper: 'Legal PPC is competitive — minimum viable budgets vary by market.',
    type: 'single',
    allowNote: true,
    options: [
      { value: 'under1k', label: 'Under $1,000 / month', score: 2 },
      { value: '1to3k', label: '$1,000 – $3,000 / month', score: 5 },
      { value: '3to7k', label: '$3,000 – $7,000 / month', score: 8 },
      { value: '7to15k', label: '$7,000 – $15,000 / month', score: 10 },
      { value: 'above15k', label: '$15,000+ / month', score: 10 },
    ],
  },
  {
    id: 'q10',
    tier: 3,
    category: 'Decision',
    question: 'What is the firm\'s decision-making timeline for engaging a new marketing partner?',
    type: 'single',
    options: [
      { value: 'asap', label: 'Immediately — they\'re ready to move now', score: 10 },
      { value: '30days', label: 'Within 30 days', score: 8 },
      { value: '90days', label: 'Within 90 days', score: 5 },
      { value: 'exploring', label: 'Just exploring options for now', score: 2 },
    ],
  },
  {
    id: 'q11',
    tier: 3,
    category: 'Pain Point',
    question: 'What is the firm\'s #1 challenge right now when it comes to growth?',
    helper: 'Understanding their pain point helps you frame PPC as the solution.',
    type: 'single',
    allowNote: true,
    options: [
      { value: 'not_enough_leads', label: 'Not enough new client inquiries', score: 10 },
      { value: 'wrong_leads', label: 'Getting leads but wrong practice area / low quality', score: 9 },
      { value: 'losing_to_competitors', label: 'Losing clients to competitors online', score: 9 },
      { value: 'no_online_presence', label: 'Weak or invisible online presence', score: 7 },
      { value: 'no_time', label: 'Too busy — no time to manage marketing', score: 6 },
      { value: 'cost', label: 'Previous marketing felt too expensive or unclear ROI', score: 8 },
    ],
  },
];